server:
  port: 8888

management:
  context-path: /admin

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
spring:
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/drbugsmn/SpringMicroSvcDemo_ConfigRepo
          uri: file:///${user.home}/Git/SpringConfigServerConfigs/SimpleExperiment #local git repo, note on windows 3 /// not 2
          #uri: https://github.com/spring-cloud-samples/config-repo #Original source
          #basedir: target/config